name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04 #job wird in einem ubunto container aufegührt
    steps:
      - name: Checkout
        uses: actions/checkout@v4 #holt sich den code vom repo
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6 #das ist eine offizielle github action von cypress die, die tests in dem workflow ausführt
                                          # die erkennt die package.json
                                          # npm i
                                          # führt die tests aus die in der cypress config definiert sind
